### ISSUE TITLE
Tambola ticket genration issue

### ISSUE THREAD

**Issue by ankitkchetu** [sidaudhi/tambola-generator#1]
![screenshot from 2017-06-19 14 20 44](https://user-images.githubusercontent.com/11932559/27277017-86585444-54fa-11e7-9b56-14d574bd3b84.png)
There is one rule missing in this package. There must be one value in each column. Please add this rule in this package. in first and second row ticket having blank value in 2 columns

**Comment by KPS250** [comment]
Each column must have at least one number.

**Comment by sidaudhi** [comment]
New version of the package (1.0.0) should have this fix. There is a breaking change to the package, so you will require a small code change to the application. This is now completely rewired to use Typescript.

var tambola = require('tambola-generator').default;
tambola.generateTickets(100)

Please check the Readme.md
